services:
  app:
    image: olsonadr/blackboard-ai
    container_name: blackboard-ai
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - saved-data:/var/lib/blackboard/data

volumes:
  saved-data:
