# This workflow will run build the project w/ docker compose, put it up and down, and if all passed, push to dockerhub.

name: Docker Compose

on:
  push:
    branches: [ deployment ]

jobs:
  build-run-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: docker compose build
      - name: Compose Up
        run: docker compose up -d
      - name: Compose Down
        run: docker compose down -v
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Push Container
        run: docker compose push
